### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by landam** [ctu-fgis/2020-b-qgis-gtfs-plugin#8]
Steps to reproduce:

* Leave input file empty
* Click on button

Fails with:

```
2020-04-14T16:05:30     WARNING    Traceback (most recent call last):
              File "/home/martin/git/ctu-fgis/2020-b-qgis-gtfs-plugin/GTFS.py", line 254, in load_file
              with ZipFile(path, 'r') as zip:
              File "/usr/lib/python3.8/zipfile.py", line 1251, in __init__
              self.fp = io.open(file, filemode)
             FileNotFoundError: [Errno 2] No such file or directory: ''
```

See also #1

**Comment by landam** [comment]
See d8061d6d8420701096c7e437969e1b5ba0154724
